blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('posts.urls')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),



]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.



class Post(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to="pics/docs/",
                              default="pics/default_post.jpg")
    desc = models.TextField(blank=False,max_length=300)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):

        super().save(force_insert, force_update, using, update_fields)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

templates/base.html
{% load static %} {% static "images" as BaseUrl %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SAFARI</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block css %} {% endblock css %}
  </head>
  {% block content %}{% endblock content %} {% block scripts %}

  {% endblock scripts %}

  <body>
  </body>
</html>

templates/create.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
{% load widget_tweaks %}
<!--  -->
{% static "images" as BaseUrl %}
<!--  -->
{% block css %}
    <meta charset="utf-8">
    <title>blogs</title>
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- FontAweome CDN Link for Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    {% endblock css %}
    <!--  -->
    {% block content %}


    <div class="container">
      <div class="wrapper">
        <section class="post">
          <header>Create new Post</header>
          <form
          class="form-horizontal form_middle"
          enctype="multipart/form-data"
          action=""
          method="post"
        >
            {% csrf_token %}
            <div class="content">
           
              <div class="details">
            </div>
            </div>
            
            <div class="input-box">
              {% render_field form.title type="text" placeholder="Title of your post" %}

             
             </div>
            {% render_field form.desc type="text" placeholder="Description" %}
            
         
              
           
                <div class="file-upload-wrapper" data-text="Select Image To Uplaod">
                
                  {% render_field form.image type="file" class="file-upload-field" %}
                </div>
              
            
                <button>Post</button>
              </form>
            </section>
            
            {% endblock content %}
            {% block script %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
            <script src="{% static 'js/create.js' %}"></script>      
        {% endblock script %}

templates/delete.html
{% extends 'base.html' %} 
{% load static %} 
{% static "images" as BaseUrl %}
{% block css %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge" />
<link rel="stylesheet" type="text/css" href="{% static 'css\delete.css' %}" />

{% endblock css %} {% block content %}


<!-- loop start here ====================================================-->
<form action="{% url 'delete_post' item.id  %}" method="POST" class="form">
  {% csrf_token %}
    <div class="card">
     
      <div class="card-image"
      style="background: url('/media/{{item.image}}');"
      ></div>
      <div class="card-text">
        
        <h2>{{item.title}}</h2>
        
    
      
        <p>{{item.desc}}</p>
        
        
        
      </div>
      <div class="created">
        <span class="owner">
          <b style="font-size:15px; " >
            {{item.created_by.get_full_name}}
                  <i class="uis uis-check-circle" style="color: #66299b"></i>

          </b><br>
          <span class="date" style="font-size:13px; color: red; ">{{item.updated_at|date:"M d, Y" }}</span>
          </span>
          
          <div class="button">

            <button class="usercontact" type="submit"> Delete</button>&nbsp;&nbsp;
            &nbsp;&nbsp;          </form>
              <button class="usercontact" type="reset" onclick ="location.href = '/';"> Cancel     
              </button>
            </div>
          </div>
      </div>

      
      



  {% endblock %} 

templates/index.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->
<!--  -->
{% block css %}

    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css\index.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css\navbar.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link
  rel="stylesheet"
  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
  crossorigin="anonymous"
/>

    {% endblock css %}
    <!--  -->
    {% block content %}
    <a href="{% url 'addpost' %}" class="float">
      <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
      <lottie-player
        src="{% static 'json/add-post.json' %}"
        background="transparent"
        speed="1"
        style="width: 60px; height: 60px"
        loop
        autoplay
      ></lottie-player>
      </a>
    <!--card1-->
    <section class="navigation  sticky">
      <div class="nav-container">
        <div class="brand" style="color: #ff8928;font-weight: 800;"> 
         SAFARI
        </div>
        <nav>
          <div class="nav-mobile"><a id="nav-toggle" href="{% url 'index' %}"><span></span></a></div>
          
          <ul class="nav-list">
            <li>
              <div class="search-form">
                  <form action="{% url 'search' %}" method="get">
                      <input type="text" name="q" placeholder="Search posts...">
                      <button type="submit">Search</button>
                  </form>
              </div>

            </li>
            <li>
              <a href="{% url 'profile' %}">
                <i class="uil uil-user-circle"></i>
                &nbsp;&nbsp;{{user.get_full_name}}</a>
            </li>
            
          </ul>
        </nav>
      </div>
    </section>
    <div class="card-container">


    <!-- Add this form where you want the search bar to appear -->


    {% for post in posts %}
<!-- loop start here ====================================================-->
    <div class="card">

      <div class="card-image"
      style="background: url('../media/{{post.image}}'); background-size: cover;
      background-repeat: no-repeat;"
      ></div>
   <div class="content">
    <div class="card-text">

      <h4>{{post.title}}</h4>


      <p>{{post.desc}}</p>



    </div>
    <div class="created">
      <span class="owner">
        <b style="font-size:15px; " >
          {{post.created_by.get_full_name}}
          {% if post.created_by.is_superuser %}
                <i class="uis uis-check-circle" style="color: #00dd11"></i>
                {% elif post.created_by.profile.verified %}
                <i class="uis uis-check-circle" style="color: #66299b"></i>
                {% else %} {% endif %}
        </b><br>
        <span class="date" style="font-size:13px; color: red; ">{{post.updated_at|date:"M d, Y" }}</span>
        </span>

        <div class="button">
          {% if userId == post.created_by.id %}
          <button class="usercontact"onclick ="location.href = 'post/update-post/{{post.id}}';"> EDIT

         
              {% endif %}

            </button>
          </div>
        </div>
   </div>
      </div>



      {% endfor %}
    </div>


      </div>
   
{% endblock content %}
{% block script %}
<!-- <script src="{% static 'js/script.js' %}"></script> -->

<script src="https://cdn.lordicon.com/lusqsztk.js"></script>
{% endblock script %}

templates/login.html
{% extends 'base.html' %} {% load static %}

<title>Document</title>
{% block css %}
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link
  href="https://fonts.googleapis.com/css?family=Montserrat:300, 400, 500"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css"
/>
<link
  rel="stylesheet"
  href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
/>

<link
  rel="stylesheet"
  id="xo-google-fonts-css"
  href="http://fonts.googleapis.com/css?family=Montserrat%3A400italic%2C400#038;ver=cc0ca1022224db4641d9750cd65dfefc"
  type="text/css"
  media="all"
/>
{% endblock css %} {% block content %}
<div class="container" id="container">
  <div class="container-2">
    <div class="wrapper-login" id="myDIV">
      <div class="form-container sign-in-container">
        <form action="login" method="post">
          {% csrf_token %}
          <div>
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player
              src="https://assets8.lottiefiles.com/packages/lf20_2nfmti0q.json"
              background="transparent"
              speed="1"
              style="width: 120px; height: 120px"
              loop
              autoplay
            ></lottie-player>
          </div>

          <h1>Log in</h1>
          <br />

          <input type="text" placeholder="username" name="username" />

          <div class="Icon-inside">
            <input
              type="password"
              placeholder="Password"
              name="password"
              value=""
              id="myInput"
            />
            <i class="uil uil-eye" onclick="myFunction3()"></i>
          </div>
          <a href="">Forgot your password?</a>

          <button name="login_form">Log In</button>
        </form>
      </div>
    </div>
    <div class="wrapper-signIn" id="myDIV1">
      <div class="form-container sign-in-container">
        <form action="signup" method="post">
          {% csrf_token %}
          <h1>Create Account</h1>

          <!--  -->
          {{ form.username }}
          <!--  -->
          {{ form.email }}
          <!--  -->
          {{ form.first_name}}
          <!--  -->
          {{form.last_name }}

          <div class="Icon-inside">
            {{ form.password1 }} {{ form.password2 }}
            <i class="uil uil-eye" onclick="myFunction4()"></i>
          </div>

          <button name="signup_form">Sign Up</button>
        </form>
      </div>
    </div>
  </div>

  <div class="overlay-container">
    <div class="overlay">
      <div class="" container-3>
        <div class="right-sign" id="r1">
          <div class="overlay-panel overlay-right">
            {% if messages %} {% for message in messages %}
            <h1>{{message}}</h1>
            <p>Wrong Password or username</p>
            {% endfor %} {% else %}
            <h1>Hello, Friend!</h1>
            <p>Enter your personal details and start journey with us</p>
            {% endif %}
            <button class="ghost" onclick="myFunction1()">Sign Up</button>
            
          </div>
        </div>
        <div class="right-log" id="r2">
          <div class="overlay-panel overlay-right">
            {% if messages %} {% for message in messages %}
            <h4>{{message}}</h4>
            Your password can’t be too similar to your other personal information.,<br>
    Your password must contain at least 8 characters.<br>
    Your password can’t be a commonly used password.<br>
    Your password can’t be entirely numeric.<br>
            {% endfor %} {% else %}
            <h1>Welcome Back!</h1>
            <p>
              To keep connected with us please login with your personal info
            </p>
            {% endif %}
            <button class="ghost" onclick="myFunction2()">login</button>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer></footer>
{% endblock content %} {% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/login.js' %}"></script>
{% endblock scripts %}

templates/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load materializecss %}
{% load static %}

{% block css %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="icon" href="{% static 'images/Earth2.jpg' %}">
<meta http-equiv="X-UA-Compatible" content="ie=edge" />  
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% endblock css %}



{% block content %}
<div class="container">
	<div class="content-section">
		<legend class="border-bottom mb-4">Password reset</legend>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	<fieldset class="form-group">
	{{form|crispy}}
	<input class="btn btn-outline-info" type="Submit" name="Send email">	
</form>
</fieldset>
</div>
</div>
{% endblock content %}

templates/password_reset_done.html
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<br><br><div class="container">
  <div class="card w-50">
    <div class="card-body">
      <h5 class="card-title">Password reset complete</h5>
      <p class="card-text">Your password has been set. You may go ahead and log in now.</p>
      <a style="background-color: #2B7A7B;" href="/" class="btn btn-primary">Log in</a>
    </div>
  </div></div>

templates/password_reset_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load materializecss %}
{% load static %}

{% block css %}
<div class="container">
	<div class="content-section">

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="icon" href="{% static 'images/Earth2.jpg' %}">
<meta http-equiv="X-UA-Compatible" content="ie=edge" />  
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% endblock css %}
  {% block content %}
  <legend class="border-bottom mb-4">Enter new password</legend>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	<fieldset class="form-group">
	{{form|crispy}}
	<input class="btn btn-outline-info" type="Submit" name="Update Password">	
</form>
</fieldset>
</div></div>
{% endblock content %}

templates/password_reset_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>MANOPO</title>
</head>
<body>
  
    <div class="card text-center">
        <div class="card-header">
          MANOPO
        </div>
        <div class="card-body">
          <h5 class="card-title">Password reset sent</h5>
          
          <p class="card-text">We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
          <p class="card-text">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
         
        </div>

        <div class="card-footer text-muted">
          
        </div>
      </div> 

</body>
</html>



<p></p>

templates/profile.html
{% extends 'base.html' %}
<!--  -->
{% load widget_tweaks %}
<!--  -->
{% load static %}
<!--  -->
{% static "images" as BaseUrl %}
<!--  -->
{% block css %}
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>

<link
  rel="stylesheet"
  href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
/>
{% endblock css %}
<!--  -->
{% block content %}
<section class="navigation sticky">
  <div class="nav-container">
    <div class="brand">
      <a href="/">
        <img src="{% static 'images\logo2.png' %}" style="display: block; margin-top: -90px; width: 50%;" />
    </a>
    
    </div>
    <nav>
      <div class="nav-mobile">
        <a id="nav-toggle" href="#!"><span></span></a>
      </div>
      <ul class="nav-list">
  
        <li>
          <a href="{% url 'profile' %}">{{user.get_full_name}}</a>
        </li>
      </ul>
    </nav>
  </div>
</section>
<div class="container" id="container">
  <div class="picture">
    <div class="dp-img">
      <img class="profile" src="{{ user.profile.image.url }}" />
    </div>
    <div class="ghost" style="color: aliceblue">{{ user.get_full_name }}</div>

    <div>
      {% for message in messages %}
      <div class="ghost" style="color: aliceblue">{{message}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="info">
    <form
      class="form2"
      method="POST"
      enctype="multipart/form-data"
      id="profileForm"
      
    >
      {% csrf_token %}
      <!-- ============================= -->

      <div>
        <h2>USER NAME</h2>
        <div class="Icon-inside">
          <div>
            <!--  -->
            {% render_field u_form.username %}
            <!--  -->
            <i class="uil uil-pen"></i>
          </div>
          <hr />
        </div>
      </div>
      <!-- ============================= -->
      <div>
        <h2>E MAIL</h2>
        <div class="Icon-inside">
          <div>
            {% render_field u_form.email type="email" %}

            <i class="uil uil-pen"></i>
          </div>
          <hr />
        </div>
      </div>
      <!-- ============================= -->
      <div>
        <h2>FIRST NAME</h2>
        <div class="Icon-inside">
          <div>
            {% if user.profile.verified %}
            <!--  -->
            {% render_field u_form.first_name|append_attr:"readonly:readonly" %}

            <i class="uis uis-check-circle" style="color: #66299b"></i>
            {% else %}
            <!--  -->
            {% render_field u_form.first_name %}
            <!--  -->
            <i class="uil uil-pen"></i>
            {% endif %}
          </div>
          <hr />
        </div>
      </div>
      <!-- ============================= -->
      <div>
        <h2>LAST NAME</h2>
        <div class="Icon-inside">
          <div>
            <!--  -->
            {% if user.profile.verified %}
            <!--  -->
            {% render_field u_form.last_name|append_attr:"readonly:readonly" %}

            <i class="uis uis-check-circle" style="color: #66299b"></i>
            {% else %}
            <!--  -->
            {% render_field u_form.last_name type="text" %}
            <!--  -->
            <i class="uil uil-pen"></i>
            {% endif %}
          </div>
          <hr />
        </div>
      </div>
      <div>
        <h2>Image</h2>
        <div class="Icon-inside">
          <div class="upload">
            {% render_field p_form.image type="file" class="upload"%}
            <i class="uil uil-pen"></i>
          </div>
          <hr />
        </div>
      </div>
      <!-- ============================= -->
      <div class="info-btns">
        <a  href="/"><button class="info-btn" type="submit">save</button></a>
        <a href="{% url 'logout' %}" class="info-a">Log out</a>
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_state").change(function () {
    const url = $("#profileForm").attr("data-states-url"); // get the url of the `load_cities` view
    const stateId = $(this).val(); // get the selected state ID from the HTML input

    $.ajax({
      // initialize an AJAX request
      url: url, // set the url of the request (= /persons/ajax/load-cities/ )
      data: {
        state_id: stateId, // add the state id to the GET parameters
      },
      success: function (data) {
        // `data` is the return of the `load_cities` view function
        //$("#id_city").html(data); // replace the contents of the city input with the data that came from the server

        let html_data = '<option value="">---------</option>';
        data.forEach(function (city) {
          console.log(city);
          html_data += `<option value="${city.id}">${city.name}</option>`;
        });
        $("#id_city").html(html_data);
      },
    });
  });
</script>
{% endblock scripts %}

templates/search_results.html
{% extends 'base.html' %}


<!--  -->
{% load static %}
<!--  -->
<!--  -->
{% block css %}

    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css\index.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css\navbar.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link
  rel="stylesheet"
  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
  crossorigin="anonymous"
/>

    {% endblock css %}


    
{% block content %}
<a href="{% url 'addpost' %}" class="float">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <lottie-player
      src="{% static 'json/add-post.json' %}"
      background="transparent"
      speed="1"
      style="width: 60px; height: 60px"
      loop
      autoplay
    ></lottie-player>
    </a>
  <!--card1-->
  <section class="navigation  sticky">
    <div class="nav-container">
      <a href="/"></a><div class="brand" style="color: #ff8928;font-weight: 800;"> 
       SAFARI
      </div>
      <nav>
        <div class="nav-mobile"><a id="nav-toggle" href="{% url 'index' %}"><span></span></a></div>
        <ul class="nav-list">
            <li>
                <div class="search-form">
                    <form action="{% url 'search' %}" method="get">
                        <input type="text" name="q" placeholder="Search posts...">
                        <button type="submit">Search</button>
                    </form>
                </div>
  
              </li>
          <li>
            <a href="{% url 'profile' %}">
              <i class="uil uil-user-circle"></i>
              &nbsp;&nbsp;{{user.get_full_name}}</a>
          </li>
        </ul>
      </nav>
    </div>
  </section>
  <div class="card-container">


  <!-- Add this form where you want the search bar to appear -->



    
    {% for post in posts %}
    <div class="card">
        <div class="card-image"
            style="background: url('/../media/{{post.image}}'); background-size: cover;
            background-repeat: no-repeat;"
        ></div>
        <div class="content">
            <div class="card-text">
                <h4>{{post.title}}</h4>
                <p>{{post.desc}}</p>
            </div>
            <div class="created">
                <span class="owner">
                    <b style="font-size:15px; " >
                        {{post.created_by.get_full_name}}
                        {% if post.created_by.is_superuser %}
                            <i class="uis uis-check-circle" style="color: #00dd11"></i>
                        {% elif post.created_by.profile.verified %}
                            <i class="uis uis-check-circle" style="color: #66299b"></i>
                        {% else %}
                        {% endif %}
                    </b><br>
                    <span class="date" style="font-size:13px; color: red; ">{{post.updated_at|date:"M d, Y" }}</span>
                </span>
                <div class="button">
                    {% if userId == post.created_by.id %}
                    <button class="usercontact" onclick="location.href = 'post/update-post/{{post.id}}';"> EDIT
                    {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
        <p>No posts found.</p>
    {% endfor %}
{% endblock content %}

templates/update.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
{% load widget_tweaks %}
<!--  -->
{% static "images" as BaseUrl %}
<!--  -->
{% block css %}
    <meta charset="utf-8">
    <title>SAFARI</title>
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- FontAweome CDN Link for Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    {% endblock css %}
    <!--  -->
    {% block content %}


    <div class="container">
      <div class="wrapper">
        <section class="post">
          <header>{{form.title.value }}</header>
          <form
          class="form-horizontal form_middle"
          enctype="multipart/form-data"
          action=""
          method="post"
        >
            {% csrf_token %}
            <div class="content">
           
              <div class="details">
            </div>
            </div>
            
            <div class="input-box">
              <label for="id_title">title</label>
              {% render_field form.title type="text" placeholder="Title of your post" %}

             
             </div>
             <label for="id_desc">description</label>

            {% render_field form.desc type="text" placeholder="Description" %}
            
   
              
           
                <div class="file-upload-wrapper" data-text="Select Image To Change">
                
                  {% render_field form.image type="file" class="file-upload-field" %}
                </div>
              
            
                <div class="btns">
                  <button type="submit">update</button>
                  <a href="{% url 'delete_post' pk %}"><button disabled><a href="{% url 'delete_post' pk %}">Delete</a></button></a>
                </div>
              </form>
            </section>
            
            {% endblock content %}
            {% block script %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
            <script src="{% static 'js/create.js' %}"></script>      
        {% endblock script %}